name: Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  bicep-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Bicep build
        run: az bicep build --file ../../main.bicep